pitanja=["Koji je prvi korak rješavanja problema?","Osim ispravnosti važno svojstvo algoritmaje:",
         "Koji jezik razumije mikroprocesor?","Pri kodiranju osim sintakse potrebno je znati:",
         "Osim logičkih pogrešaka imamo i:","Jezične prevoditelje dijelimo na: interpretere i",
         "Za prijelaz u novi red koristimo varijablu:","varijabla % vraća:",
         "Koja funkcija služi za unos:","Kada znamo broj ponavljanja petlje koristimo:",
         "Prije korištenja naredbe randint moramo","Prvi znak u stringu ima oznaku:",
         "Koja je funkcija za dodavanje elemanata u listu?","za pravljanje vlastitih funkciju koristimo:",
         "Koja je metoda za čitanje datoteke?","Za mjerenje vremena moramo importat modul:",
         "program zaustavljamo na određeno vrijeme funkcijom:","Struktura podataka poznata kao LIFO je",
         "Sortiranje zamjenom susjednih elemenata je:","najbrže sortiranje je:","graf se satsoji od grana i:",
         "modul za grafičko sučelje je:","modul za crtanje je:","najstarije programsko računalo je:",
         "prije pocetka programiranja moramo:","elemente u grafickom sucelju smjestamo po redovima i stupcima naredbom:",
         "tekst na grafičko sučelje ispisujemo naredbom:","boju u pozadini teksta mijenjamo parametrom:",
         "kada ne znamo broj ponavljanja petlje koristimo naredbu:","računalo se sastoji od:"]
a=["Odabir algoritma i zasnivanje programa.","Trajanje.","Strojni","Morfologiju",
   "Gramatičke","Kompresore","'\,n'","cjeli broj","input","for",
   "popiti vode","S[1]","add","def","'W'","Time","stop","Red",
   "bubble sort","quick sort","Debla","thinker","turtle","Edvac",
   "upaliti python","place","print","bg","for","Kućišta i monitora"]
b=["Analiza zahtjeva.","Složenost.","Viši programski jezik","Fonetiku",
   "sintaktičke","Tumače","'\,t'","Ostatak cjelobrojnog dijeljenja","int","while",
   "Pogoditi broj","S[0]","put in","make","'r'","Clock","break","stog",
   "exchange sort","ugrađeno sortiranje","korijena","toughter","paint","Eniac",
   "znati programirati","grid","label","fg","when","hardvera i softvera"]
c=["Specifikacija problema.","Jednostavnost.","Hrvatski","Semantiku",
   "Matematičke","Kompajlere","'\,\'","Postotak","bin","when",
   "importat random","S[prvi]","append","class","'a'","Random","sleep","stablo",
   "quick sort","bucket sort","čvorova","tkinter","color","Alienware area 51",
   "upaliti kompjuter","pack","text","color","while","miša i tipkovnice"]
odgovori=["B","A","A","C","B","C","A","B","A","A","C","B","C","A","B","A","C","B",
          "A","B","C","C","A","B","C","B","B","A","C","B"]
